config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users
    
  root to: "pages#home"
  get "listings", to: "listings#index", as: "listings"
  post "listings", to: "listings#create"
  get "listings/new", to: "listings#new", as: "new_listing"
  get "listings/:id", to: "listings#show", as: "listing"
  put "listings/:id", to: "listings#update"
  patch "listings/:id", to: "listings#update"
  delete "listings/:id", to: "listings#destroy", as: "destroy_listing"
  get "listings/:id/edit", to: "listings#edit", as: "edit_listing"
  get "payments/success/:id", to: "payments#success", as: "payments_success"
  post "payments/webhook", to: "payments#webhook"

end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :listings_features, dependent: :destroy
  has_many :features, through: :listings_features

  enum condition: {brand_new: 1, used_excellent: 2, used_good: 3, used_ok: 4}

  has_one_attached :photo

  # data validations
  validates :title, presence: true, length: {maximum: 50}
  validates :price, presence: true, numericality: {only_integer: true}, length: {maximum: 6}
  validates :description, presence: true, length: {maximum: 255}
  validates :postcode, presence: true, numericality: {only_integer: true}, length: {is: 4}
  validates :brand, :model, :finish, presence: true, length: {maximum: 50}
  validates :capacity, :height, :width, :depth, length: {maximum: 4}

# Active Record callback
  before_save :remove_whitespace
  before_validation :convert_price_to_cents, if: :price_changed?

  private
  def remove_whitespace
    self.title = self.title.strip
    self.description = self.description.strip
    self.brand = self.brand.strip
    self.model = self.model.strip
    self.finish = self.finish.strip
  end

  def convert_price_to_cents
    self.price = self.price.to_i * 100
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :define_listing, only: [:show, :edit, :update, :destroy]
  before_action :authorize_user, only: [:edit, :update, :destroy]
  before_action :define_form_variables, only: [:new, :edit]
  
  def index
    # Capture all records in the listings table by querying the listings table through the Listing model
    @listings = Listing.all
  end

  def show
    # Create Stripe session, capture certain payment data, and set up redirect URLs
    session = Stripe::Checkout::Session.create(
      payment_method_types: ['card'],
      customer_email: current_user && current_user.email,
      line_items: [
        {
          name: @listing.title,
          description: @listing.description,
          amount: @listing.price,
          currency: 'aud',
          quantity: 1
        }
      ],
      payment_intent_data: {
        metadata: {
          user_id: current_user && current_user.id, 
          listing_id: @listing.id
        }
      },
      success_url: "#{root_url}payments/success/#{@listing.id}",
      cancel_url: root_url
    )

    # Capture Stripe session id
    @session_id = session.id

  end

  def new
    # Create new record in listings table by querying the listings table through the Listing model
    @listing = Listing.new
  end

  def create
    # Create new record in listings table under the current_user (as defined by the Devise gem) and alert user of any error creating the listing
    @listing = current_user.listings.new(listing_params)
    if @listing.save
        redirect_to @listing, notice: "You have successfully created a listing"
    else
      define_form_variables
      render "new", alert: "Error creating listing. Ensure all fields are filled out correctly."
    end
  end

  def edit
  end

  def update
    # Update record in listings table and alert user of any error updating the listing
    @listing.update(listing_params)
    if @listing.save
        redirect_to @listing, notice: "You have successfully updated the listing"
    else
      define_form_variables
      render "edit", alert: "Error creating listing. Ensure all fields are filled out correctly."
    end
  end

  def destroy
    # Delete listing
    @listing.destroy
    redirect_to listings_path, notice: "You have successfully deleted the listing"
  end

  private

  def define_listing
    # Capture the specific listing determined by parameter id
    @listing = Listing.find(params[:id])
  end

  def authorize_user
    # Prevent unauthorized users from accessing edit, update and destroy actions (utilising a before_action)
    unless @listing.user_id == current_user.id
      redirect_to listings_path, alert: "You are not authorised to access that page"
    end
  end

  def define_form_variables
    # Capture (for use in the form): (1) all records in the categories table by querying the categories table through the Category model; (2) the keys of the 'condition' enum that is set in the Listing model by querying the Listing model; and (3) all records in the features table by querying the features table through the Feature model
    @categories = Category.all
    @conditions = Listing.conditions.keys
    @features = Feature.all
  end
  
  def listing_params
    # Whitelist acceptable parameters for a listing
    params.require(:listing).permit(:title, :description, :price, :condition, :postcode, :brand, :model, :finish, :capacity, :height, :width, :depth, :energy_efficiency, :category_id, :photo, feature_ids: [])
  end
end

app/helpers/listings_helper.rb
module ListingsHelper
    def format_price(price)
        "$#{price/100}"    end
    def format_condition(condition)
        if condition == "brand_new"
            condition.gsub("_", " ").capitalize
        else
            condition.gsub("_", " - ").capitalize
        end
    end

    def display_photo(listing)
        if listing.photo.attached?
            image_tag listing.photo, alt: listing.title, class:"thumbnail card-img top"
        else
            image_tag "default_fridge", alt: "stock image of refridgerator", class:"thumbnail card-img top"
        end
    end
end

app/views/listings/_form.html.erb
<%=form_with model: @listing, local: true do |form|%>

    <%=render "listing_errors"%>

    <div class="form-group font-weight-bold mb-3">
        <%=form.label :category_id, class: "form-label"%>
        <%=form.select :category_id, @categories.map {|category| [category.name, category.id]}, class: "form-select"%>
    </div>

    <div class="form-group font-weight-bold mb-3">
        <%=form.label :title, class: "form-label"%>
        <%=form.text_field :title, maxlength: 50, size: 40%>
    </div>

    <div class="form-group font-weight-bold mb-3">
        <%=form.label :price, "Price $", class: "form-label"%>
        <%=form.number_field :price, step: "1", max: 999999%>
    </div>

    <div class="form-group font-weight-bold mb-3">
        <%=form.label :photo, class: "form-label"%>
        <%=form.file_field :photo, accept: "image/png,image/jpg,image/jpeg", class: "form-select"%>
    </div>

    <p class="font-weight-bold d-inline">Condition &nbsp&nbsp</p>
    <%@conditions.each do |c|%>
        <%=form.label :condition, format_condition(c), class: "form-label mr-1" %>
        <%=form.radio_button :condition, c, class:"mr-4"%>
    <%end%>

    <div class="form-group font-weight-bold mb-3">
        <%=form.label :description, class: "form-label"%>
        <%=form.text_area :description, class: "form-control", maxlength: 255%>
    </div>

    <p class="font-weight-bold d-inline mb-3">Features</p>
    <div class="form-check form-check-line mb-3 ml-2">
        <%=form.collection_check_boxes :feature_ids, @features, :id, :name  do |block|%>
            <%=block.label class: "form-check-label"%>
            <%=block.check_box class: "form-check-line mr-4"%>
        <%end%>
    </div>

    <div class="form-group font-weight-bold mb-3">
        <%=form.label :postcode, "Location (postcode)", class: "form-label"%>
        <%=form.number_field :postcode, max: 9999%>
    </div>

    <div class="form-group font-weight-bold mb-3">
        <%=form.label :brand, class: "form-label"%>
        <%=form.text_field :brand, maxlength: 50, size: 40%>
    </div>

    <div class="form-group font-weight-bold mb-3">
        <%=form.label :model, class: "form-label"%>
        <%=form.text_field :model, maxlength: 50, size: 40%>
    </div>

    <div class="form-group font-weight-bold mb-3">
        <%=form.label :finish, "Finish (colour and material)", class: "form-label"%>
        <%=form.text_field :finish, maxlength: 50, size: 40%>
    </div>

    <div class="form-group font-weight-bold mb-3">
        <%=form.label :capacity, "Capacity (litres)", class: "form-label"%>
        <%=form.number_field :capacity, max: 9999%>
    </div>

    <div class="form-group font-weight-bold mb-3">
        <%=form.label :height, "Height (mm)", class: "form-label"%>
        <%=form.number_field :height, max: 9999%>
    </div>

    <div class="form-group font-weight-bold mb-3">
        <%=form.label :width, "Width (mm)", class: "form-label"%>
        <%=form.number_field :width, max: 9999%>
    </div>

    <div class="form-group font-weight-bold mb-3">
        <%=form.label :depth, "Depth (mm)", class: "form-label"%>
        <%=form.number_field :depth, max: 9999%>
    </div>

    <p class="font-weight-bold mb-1">Energy-efficiency rating</p>
        <%=form.label :energy_efficiency, 1, class: "form-label mr-1" %>
        <%=form.radio_button :energy_efficiency, 1, class:"mr-3"%>
        <%=form.label :energy_efficiency, 2, class: "form-label mr-1" %>
        <%=form.radio_button :energy_efficiency, 2, class:"mr-3"%>
        <%=form.label :energy_efficiency, 3, class: "form-label mr-1" %>
        <%=form.radio_button :energy_efficiency, 3, class:"mr-3"%>
        <%=form.label :energy_efficiency, 4, class: "form-label mr-1" %>
        <%=form.radio_button :energy_efficiency, 4, class:"mr-3"%>
        <%=form.label :energy_efficiency, 5, class: "form-label mr-1" %>
        <%=form.radio_button :energy_efficiency, 5, class:"mr-3"%>

    <div class="actions my-4">
        <%=form.submit%>
    </div>
<%end%>

app/views/listings/_listing_errors.html.erb
<%if @listing.errors.any?%>
    <div class="alert alert-error alert-dismissable fade show">
        <h5><%=pluralize(@listing.errors.count, "error")%> completing the form</h5>
        <ul>
            <%@listing.errors.full_messages.each do |message|%>
                <li><%=message%></li>
            <%end%>
        </ul>

        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
<%end%>

app/views/listings/edit.html.erb
<div style="background-color: #F2F6F4">
    <h2 class="text-center display-4po b text-muted mb-sm-2 mb-md-3 p-4">Update listing</h2>
    <div class="p-5">
        <%=render "form"%>
    </div>
</div>

app/views/listings/index.html.erb
<div style="background-color: #F2F6F4">
    <h1 class="text-center display-4po b text-muted p-5">All Refrigerators and Freezers Listed</h1>
    <section class="container">
        <div class="row row-cols-sm-1 row-cols-md-2 row-cols-lg-3">
            <%@listings.each do |listing|%>
            <div class="row col p-5">
                <div class="card-img-top h-50">
                    <%=display_photo(listing)%>
                    <div class="card-body">
                        <p class="card-text font-weight-bold"><%=format_price(listing.price)%></p>
                        <p class="card-text font-weight-bold"><%=link_to "#{listing.title}", listing_path(listing.id)%></p>
                    </div>
                </div>
            </div>
            <%end%>
        </div>
    </section>
</div>

app/views/listings/new.html.erb
<div style="background-color: #F2F6F4">
    <h2 class="text-center display-4po b text-muted mb-sm-2 mb-md-3 p-4">Create listing</h2>
    <div class="p-5">
        <%=render "form"%>
    </div>
</div>

app/views/listings/show.html.erb
<div style="background-color: #F2F6F4">
    <section class="container d-flex flex-column flex-lg-row p-5">

        <div class="sidebar col-lg-4 p-0 mx-2 d-md-block"> 
            <h2 class="text-center display-4po b text-muted mb-sm-2 mb-md-3"><%=@listing.title%></h2>

            <p></p>
            <p class="text-muted font-weight-bold d-inline">Category &nbsp&nbsp&nbsp</p><p><%=@listing.category.name%></p>
            <p class="text-muted font-weight-bold d-inline">Price &nbsp&nbsp&nbsp</p><p><%=format_price(@listing.price)%></p>

            <p></p>
            <p class="text-muted font-weight-bold">Features &nbsp&nbsp&nbsp</p>
            <%@listing.features.each do |feature|%>
                <span class="badge badge-pill badge-light mb-sm-2 mb-md-3 p-2"><%=feature.name%></span>
            <%end%>
            
            <p></p>
            <p class="text-muted font-weight-bold d-inline">Condition &nbsp&nbsp&nbsp</p><p><%=format_condition(@listing.condition)%></p>
            <p class="text-muted font-weight-bold d-inline">Description &nbsp&nbsp&nbsp</p><p><%=@listing.description%></p>
            <p class="text-muted font-weight-bold d-inline">Location (postcode) &nbsp&nbsp&nbsp</p><p><%=@listing.postcode%></p>
            <p class="text-muted font-weight-bold d-inline">Brand &nbsp&nbsp&nbsp</p><p><%=@listing.brand%></p>
            <p class="text-muted font-weight-bold d-inline">Model &nbsp&nbsp&nbsp</p><p><%=@listing.model%></p>
            <p class="text-muted font-weight-bold d-inline">Finish &nbsp&nbsp&nbsp</p><p><%=@listing.finish%></p>

            <%if @listing.capacity%>
                <p class="text-muted font-weight-bold d-inline">Capacity &nbsp&nbsp&nbsp</p><p><%=@listing.capacity%> litres</p>
            <%end%>
            <%if @listing.height%>
                <p class="text-muted font-weight-bold d-inline">Height &nbsp&nbsp&nbsp</p><p><%=@listing.height%>mm</p>
            <%end%>
            <%if @listing.width%>        
                <p class="text-muted font-weight-bold d-inline">Width &nbsp&nbsp&nbsp</p><p><%=@listing.width%>mm</p>
            <%end%>
            <%if @listing.depth%>
                <p class="text-muted font-weight-bold d-inline">Depth &nbsp&nbsp&nbsp</p><p><%=@listing.depth%>mm</p>
            <%end%>
            <%if @listing.energy_efficiency%>
                <p class="text-muted font-weight-bold d-inline">Energy-efficiency rating (out of 5) &nbsp&nbsp&nbsp</p><p><%=@listing.energy_efficiency%></p>
            <%end%>

            <%if current_user && current_user.id == @listing.user_id%>
                <div class="d-flex justify-content-equally">
                    <%if @listing.sold == false%>
                        <%=link_to "Edit", edit_listing_path(@listing.id), class: "btn btn-dark p-2 mb-3 mr-3"%>
                    <%end%>
                    <%= link_to "Delete", @listing, method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-dark p-2 mb-3 mr-3"%>
                </div>
            <%end%>

            <%if current_user && current_user.id != @listing.user_id && @listing.sold == false%>
                <button class="btn btn-dark p-2 mb-3 mr-3" data-stripe="payment">Buy (<%=format_price(@listing.price)%>)</button>
            <%elsif @listing.sold%>
                <button class="btn btn-light p-2 mb-3 mr-3" disabled>Sold</button>
            <%elsif current_user && current_user.id == @listing.user_id%>
            <%else%>
                <%=button_to "Sign in to buy", new_user_session_path, class: "btn btn-dark p-2 mb-3 mr-3"%>
            <%end%>
        </div>
        
        <div class="content col-12 col-md-7 col-lg-8 p-0 pr-md-3">
            <div class="col-12 p-0 main-preview mb-4">
                <%=display_photo(@listing)%>
            </div>
        </div>

    </section>


    <script src="https://js.stripe.com/v3/"></script>
    <script>
    document
        .querySelector("[data-stripe='payment']")
        .addEventListener("click", () => {
            const stripe = Stripe("<%=Rails.application.credentials.dig(:stripe, :public_key)%>");
            console.log(stripe);
            stripe.redirectToCheckout({
                sessionId: "<%=@session_id%>"
            })
        })
    </script>
</div>