config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users
    
  root to: "pages#home"
  get "listings", to: "listings#index", as: "listings"
  post "listings", to: "listings#create"
  get "listings/new", to: "listings#new", as: "new_listing"
  get "listings/:id", to: "listings#show", as: "listing"
  put "listings/:id", to: "listings#update"
  patch "listings/:id", to: "listings#update"
  delete "listings/:id", to: "listings#destroy", as: "destroy_listing"
  get "listings/:id/edit", to: "listings#edit", as: "edit_listing"
  get "payments/success/:id", to: "payments#success", as: "payments_success"
  post "payments/webhook", to: "payments#webhook"

end

app/views/shared/_alerts.html.erb
<%flash.each do |key, value|%>
    <div class="alert alert-<%=assign_alert_class(key)%> alert-dismissible fade show" role="alert">
        <%=value%>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
<%end%>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg sticky-top navbar-light" style="background-color: #F2F6F4">
    <div class="container-fluid">
        <%=link_to "Fridges For All", root_path, class: "navbar-brand"%>
    </div>
    <div>
        <ul class="navbar-nav mr-5-lg">
            <li class="nav-item">
                <%=link_to "All Listings", listings_path%>
            </li>
                <%if user_signed_in?%>
            <li class="nav-item">
                    <%=link_to "Create listing", new_listing_path%>
            </li>
            <li class="nav-item">
                    <%=link_to "Sign out", destroy_user_session_path, method: :delete%>
            </li>
                <%else%>
            <li class="nav-item">
                    <%=link_to "Sign in", new_user_session_path%>
            <li>
                <%end%>
        </ul>
    </div>
</nav>